[repository]
name = "hypr-radiant"
authors = ["Nika Sumbadze (@nsumbadze)"]
commit_pins = [
    ["39d7e209c79d451efab1b21151d5938289da838d", "f6780875b199e4a40bc1625e0a151b699a445748"]
]

[hypr-radiant]
description = "Native workspace overview with live previews, gestures, and search."
authors = ["Nika Sumbadze (@nsumbadze)"]
output = "build/hypr-radiant.so"
build = [
    "cmake -S . -B build -DCMAKE_BUILD_TYPE=Release",
    "cmake --build build"
]
